# Copyright © 2022-2023 The async_main crate contributors.
#
# Licensed under any of:
#  - Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
#  - Boost Software License, Version 1.0 (https://www.boost.org/LICENSE_1_0.txt)
#  - MIT License (https://mit-license.org/)
# At your choosing (See accompanying files LICENSE_APACHE_2_0.txt,
# LICENSE_MIT.txt and LICENSE_BOOST_1_0.txt).

[workspace]
members = [".", "macro"]
default-members = [".", "macro"]

[workspace.package]
version = "0.4.0"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
edition = "2021"

[package]
name = "async_main"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "Runtime-agnostic async main proc macro"
repository = "https://github.com/ardaku/async_main"
documentation = "https://docs.rs/async_main"
homepage = "https://github.com/ardaku/async_main/blob/stable/CHANGELOG.md"
include = ["/src/**", "/examples/**", "/README.md"]
keywords = ["async", "platform-agnostic", "cross-platform", "executor", "main"]
categories = ["asynchronous", "embedded", "no-std", "rust-patterns", "wasm"]
readme = "README.md"

[dependencies]
async_main_macro = "0.4"

[dependencies.async-executor]
version = "1.5"
optional = true
default-features = false

[dependencies.async-std]
version = "=1.12.0"
optional = true
default-features = false
features = ["unstable", "default"]

[dependencies.futures]
version = "0.3"
optional = true
default-features = false
features = ["executor"]

[dependencies.futures-lite]
version = "1.12"
optional = true
default-features = false

[dependencies.pasts]
version = "0.14"
optional = true
default-features = false

[dependencies.tokio]
version = "1.23"
optional = true
default-features = false
features = ["rt"]

[features]
default = []

async-executor = ["dep:async-executor", "dep:futures-lite"]
async-std = ["dep:async-std"]
futures = ["dep:futures"]
pasts = ["dep:pasts"]
tokio = ["dep:tokio"]

web = ["async_main_macro/web"]

[package.metadata.docs.rs]
features = ["pasts"]
